name: Meteo Dronero
on:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: 44.4667
      lon: 7.3524
      units: metric
      lang: it
    every: "0 7 * * *"
    timeZone: UTC
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *Meteo di oggi a Dronero*: 
              - Condizioni: ${{on.weather.outputs.current.weather[0].description}}
              - Temperatura minima: ${{on.weather.outputs.daily[0].temp.min}}
              - Temperatura massima: ${{on.weather.outputs.daily[0].temp.max}}
              - Umidità: ${{on.weather.outputs.daily[0].humidity}}%
          format: markdown
