on:
  rss:
    url: https://ivanmorgillo.com/feed/
jobs:
  print:
    name: Ivan's Blog
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}        
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo link: $link
